package it.paolofree.manutenzionemoto;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.view.animation.AnimationUtils;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;
import androidx.core.content.ContextCompat;
import java.text.*;
import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.json.JSONObject;
import android.graphics.pdf.PdfDocument;
import android.graphics.Paint;
import android.content.res.ColorStateList;

public class MainActivity extends AppCompatActivity {
    MaintenanceDb db; List<MaintenanceDb.Entry> entries=new ArrayList<>(); List<MaintenanceDb.Deadline> deadlines=new ArrayList<>(); List<MaintenanceDb.Bike> bikes=new ArrayList<>(); MaintenanceDb.Bike currentBike; ImageView bikeBackgroundImage; ListView list; TextView empty,currentKmText,activeBikeText; String filter=null; boolean showDeadlines=false; int currentKm; Uri pendingPhoto; ActivityResultLauncher<String> openJson; ActivityResultLauncher<String[]> openPhoto,openBackground; ActivityResultLauncher<String> createJson,createCsv,createPdf;
    final NumberFormat euro=NumberFormat.getCurrencyInstance(Locale.ITALY);

    @Override public void onCreate(Bundle b){ super.onCreate(b); setContentView(R.layout.activity_main); registerLaunchers(); applyKeepScreenSetting();
        db=new MaintenanceDb(this); list=findViewById(R.id.list);empty=findViewById(R.id.emptyText);currentKmText=findViewById(R.id.currentKmText);activeBikeText=findViewById(R.id.activeBikeText);bikeBackgroundImage=findViewById(R.id.bikeBackgroundImage);
        loadBikes(0); createNotificationChannel(); requestNotificationPermission();
        findViewById(R.id.settingsButton).setOnClickListener(v->showSettings());
        findViewById(R.id.updateKmButton).setOnClickListener(v->updateCurrentKm());
        findViewById(R.id.addButton).setOnClickListener(v->{if(showDeadlines)editDeadline(null);else edit(null);});
        ((RadioGroup)findViewById(R.id.sectionGroup)).setOnCheckedChangeListener((g,id)->{showDeadlines=id==R.id.sectionDeadlines;findViewById(R.id.filterGroup).setVisibility(showDeadlines?View.GONE:View.VISIBLE);((Button)findViewById(R.id.addButton)).setText(showDeadlines?"＋  NUOVA SCADENZA":"＋  NUOVO INTERVENTO");refresh();});
        ((RadioGroup)findViewById(R.id.filterGroup)).setOnCheckedChangeListener((g,id)->{filter=id==R.id.filterShop?"Officina":id==R.id.filterMe?"Io":null; refresh();});
        list.setOnItemClickListener((p,v,pos,id)->{if(showDeadlines)editDeadline(deadlines.get(pos));else edit(entries.get(pos));});
        list.setOnItemLongClickListener(null); refresh();
        showOpeningAnimation();
    }
    void refresh(){ if(currentBike==null)return;entries=db.all(currentBike.id,filter); deadlines=db.deadlines(currentBike.id);
        boolean none=showDeadlines?deadlines.isEmpty():entries.isEmpty(); empty.setText(showDeadlines?"Nessuna scadenza impostata\nPremi + per aggiungerne una":"Nessun intervento registrato\nPremi + per iniziare");empty.setVisibility(none?View.VISIBLE:View.GONE);list.setVisibility(none?View.GONE:View.VISIBLE);list.setAdapter(showDeadlines?new DeadlineAdapter():new EntryAdapter()); }
    TextView label(String s){ TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.rgb(156,179,195));t.setPadding(0,12,0,3);return t; }
    EditText input(String hint,int type){ EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(120,145,160));e.setInputType(type);e.setBackgroundResource(R.drawable.bg_input);return e; }
    void edit(MaintenanceDb.Entry old){ edit(old,null); }
    void edit(MaintenanceDb.Entry old,MaintenanceDb.Deadline completed){
        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(45,5,45,0);
        EditText part=input("es. Olio e filtro",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);
        EditText km=input("es. 25000",InputType.TYPE_CLASS_NUMBER); EditText cost=input("es. 89,50",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); Button photo=new Button(this);photo.setText("📎  ALLEGA SCONTRINO");
        RadioGroup who=new RadioGroup(this);who.setOrientation(RadioGroup.HORIZONTAL); RadioButton shop=new RadioButton(this);shop.setText("Officina");shop.setTextColor(Color.WHITE); RadioButton me=new RadioButton(this);me.setText("Io");me.setTextColor(Color.WHITE);who.addView(shop);who.addView(me);shop.setChecked(true);
        box.addView(label("PEZZO / INTERVENTO"));box.addView(part);box.addView(label("CHILOMETRI"));box.addView(km);box.addView(label("COSTO (€)"));box.addView(cost);box.addView(label("ESEGUITO DA"));box.addView(who);box.addView(photo);
        pendingPhoto=old!=null&&!old.photoUri.isEmpty()?Uri.parse(old.photoUri):null;photo.setOnClickListener(v->openPhoto.launch(new String[]{"image/*"}));
        km.setText(String.valueOf(old==null?currentKm:old.km));if(completed!=null)part.setText(completed.title);
        if(old!=null){part.setText(old.part);cost.setText(String.format(Locale.ITALY,"%.2f",old.cost));(old.who.equals("Io")?me:shop).setChecked(true);if(pendingPhoto!=null)photo.setText("✓  SCONTRINO ALLEGATO");}
        AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Nuovo intervento":"Modifica intervento").setView(box).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();
        d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
            String p=part.getText().toString().trim(),ks=km.getText().toString().trim(),cs=cost.getText().toString().trim().replace(',','.');
            if(p.isEmpty()){part.setError("Inserisci il pezzo o intervento");return;} if(ks.isEmpty()){km.setError("Inserisci i km");return;} if(cs.isEmpty()){cost.setError("Inserisci il costo");return;}
            try{int kval=Integer.parseInt(ks);double cval=Double.parseDouble(cs);String w=me.isChecked()?"Io":"Officina";long date=old==null?System.currentTimeMillis():old.dateTs;db.save(old==null?null:old.id,currentBike.id,p,kval,cval,w,date,pendingPhoto==null?"":pendingPhoto.toString());if(kval>currentKm){currentKm=kval;currentBike.km=kval;db.updateBikeKm(currentBike.id,kval);currentKmText.setText(String.format(Locale.ITALY,"%,d km",kval));}if(completed!=null)db.completeDeadline(completed.id,kval);d.dismiss();checkDeadlines();refresh();}catch(Exception ex){cost.setError("Valore non valido");}
        }));d.show();styleDialogButtons(d);
    }
    void styleDialogButtons(AlertDialog d){Button positive=d.getButton(AlertDialog.BUTTON_POSITIVE),negative=d.getButton(AlertDialog.BUTTON_NEGATIVE),neutral=d.getButton(AlertDialog.BUTTON_NEUTRAL);if(positive!=null){positive.setTextColor(Color.rgb(75,196,255));positive.setTypeface(null,android.graphics.Typeface.BOLD);}if(negative!=null){negative.setTextColor(Color.WHITE);negative.setTypeface(null,android.graphics.Typeface.BOLD);}if(neutral!=null){neutral.setTextColor(Color.WHITE);neutral.setTypeface(null,android.graphics.Typeface.BOLD);}}
    AlertDialog showStyled(AlertDialog.Builder builder){AlertDialog d=builder.create();d.show();styleDialogButtons(d);return d;}
    void confirmDelete(MaintenanceDb.Entry e){showStyled(new AlertDialog.Builder(this).setTitle("Eliminare?").setMessage(e.part+" verrà cancellato.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA",(d,w)->{db.delete(e.id);refresh();}));}
    void updateCurrentKm(){final EditText km=input("Chilometri attuali",InputType.TYPE_CLASS_NUMBER);km.setText(String.valueOf(currentKm));FrameLayout wrap=new FrameLayout(this);wrap.setPadding(45,5,45,0);wrap.addView(km);AlertDialog d=new AlertDialog.Builder(this).setTitle("Km • "+currentBike.name).setView(wrap).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{int value=Integer.parseInt(km.getText().toString());if(value<0)throw new Exception();currentKm=value;currentBike.km=value;db.updateBikeKm(currentBike.id,value);currentKmText.setText(String.format(Locale.ITALY,"%,d km",value));d.dismiss();checkDeadlines();refresh();}catch(Exception ex){km.setError("Inserisci chilometri validi");}}));d.show();styleDialogButtons(d);}
    void editDeadline(MaintenanceDb.Deadline old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(45,5,45,0);EditText title=input("es. Cambio olio",1|16384),target=input("0 = solo tempo",2),months=input("mesi alla scadenza",2),repeatKm=input("es. ogni 10000 km",2),repeatMonths=input("es. ogni 24 mesi",2),pre=input("preavviso km",2);box.addView(label("INTERVENTO"));box.addView(title);box.addView(label("SCADENZA A KM (0 se non serve)"));box.addView(target);box.addView(label("SCADENZA TRA MESI (0 se non serve)"));box.addView(months);box.addView(label("RICORRENZA KM"));box.addView(repeatKm);box.addView(label("RICORRENZA MESI"));box.addView(repeatMonths);box.addView(label("PREAVVISO KM"));box.addView(pre);pre.setText("500");if(old!=null){title.setText(old.title);target.setText(""+old.targetKm);repeatKm.setText(""+old.intervalKm);repeatMonths.setText(""+old.intervalMonths);pre.setText(""+old.prewarnKm);if(old.dueTs>0){Calendar a=Calendar.getInstance(),b=Calendar.getInstance();b.setTimeInMillis(old.dueTs);months.setText(""+Math.max(0,(b.get(Calendar.YEAR)-a.get(Calendar.YEAR))*12+b.get(Calendar.MONTH)-a.get(Calendar.MONTH)));}}AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Nuova scadenza":"Modifica scadenza").setView(box).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{try{String t=title.getText().toString().trim();int k=num(target),m=num(months),ik=num(repeatKm),im=num(repeatMonths),pv=num(pre);if(t.isEmpty()){title.setError("Inserisci l'intervento");return;}if(k==0&&m==0){target.setError("Indica km oppure mesi");return;}long due=0;if(m>0){Calendar c=Calendar.getInstance();c.add(Calendar.MONTH,m);due=c.getTimeInMillis();}db.saveDeadline(old==null?null:old.id,currentBike.id,t,k,due,ik,im,pv);d.dismiss();checkDeadlines();refresh();}catch(Exception ex){target.setError("Controlla i valori");}}));d.show();styleDialogButtons(d);}
    int num(EditText e){String s=e.getText().toString().trim();return s.isEmpty()?0:Integer.parseInt(s);}
    void confirmDeleteDeadline(MaintenanceDb.Deadline e){showStyled(new AlertDialog.Builder(this).setTitle("Eliminare scadenza?").setMessage(e.title+" verrà cancellata.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA",(d,w)->{db.deleteDeadline(e.id);refresh();}));}
    void createNotificationChannel(){if(android.os.Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("maintenance_due","Scadenze manutenzione",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Avvisi al raggiungimento dei chilometri");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    void requestNotificationPermission(){if(android.os.Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},100);}
    void checkDeadlines(){long now=System.currentTimeMillis();for(MaintenanceDb.Deadline e:db.deadlines(currentBike.id)){int rem=e.targetKm>0?e.targetKm-currentKm:Integer.MAX_VALUE;boolean due=(e.targetKm>0&&rem<=0)||(e.dueTs>0&&now>=e.dueTs);boolean soon=!due&&((e.targetKm>0&&rem<=e.prewarnKm)||(e.dueTs>0&&e.dueTs-now<=30L*86400000));int state=due?2:soon?1:0;if(state>e.notifyState){notifyDeadline(e,due,rem);db.setNotifyState(e.id,state);}}}
    void notifyDeadline(MaintenanceDb.Deadline e,boolean due,int rem){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,(int)e.id,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);String detail=e.targetKm>0?(due?"Scadenza raggiunta":String.format(Locale.ITALY,"Mancano %,d km",Math.max(0,rem))):(due?"Scadenza temporale raggiunta":"Scadenza entro 30 giorni");NotificationCompat.Builder n=new NotificationCompat.Builder(this,"maintenance_due").setSmallIcon(R.drawable.ic_launcher).setContentTitle(currentBike.name+" • "+e.title).setContentText(detail).setPriority(NotificationCompat.PRIORITY_HIGH).setAutoCancel(true).setContentIntent(pi);if(ContextCompat.checkSelfPermission(this,android.Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)NotificationManagerCompat.from(this).notify((int)e.id,n.build());}
    void loadBikes(long selectId){bikes=db.bikes();if(bikes.isEmpty()){db.addBike("La mia moto");bikes=db.bikes();}if(selectId==0)selectId=getPreferences(MODE_PRIVATE).getLong("active_bike",bikes.get(0).id);int pos=0;for(int i=0;i<bikes.size();i++)if(bikes.get(i).id==selectId)pos=i;currentBike=bikes.get(pos);getPreferences(MODE_PRIVATE).edit().putLong("active_bike",currentBike.id).apply();int old=getPreferences(MODE_PRIVATE).getInt("current_km",0);if(currentBike.id==1&&currentBike.km==0&&old>0){db.updateBikeKm(1,old);currentBike.km=old;getPreferences(MODE_PRIVATE).edit().remove("current_km").apply();}currentKm=currentBike.km;activeBikeText.setText(currentBike.name);currentKmText.setText(String.format(Locale.ITALY,"%,d km",currentKm));applyBikeBackground();refresh();}
    void showSettings(){showStyled(new AlertDialog.Builder(this).setTitle("Impostazioni").setItems(new String[]{"Cambio moto","Sfondo moto","Statistiche spese","Esporta PDF / CSV","Backup e ripristino","Schermo sempre acceso","Versione e firma"},(d,w)->{if(w==0)changeBike();else if(w==1)chooseBikeBackground();else if(w==2)showStats();else if(w==3)exportMenu();else if(w==4)backupMenu();else if(w==5)toggleKeepScreen();else showAppInfo();}).setNegativeButton("CHIUDI",null));}
    void chooseBikeBackground(){String key="bike_background_"+currentBike.id;int selected=getPreferences(MODE_PRIVATE).getInt(key,0);showStyled(new AlertDialog.Builder(this).setTitle("Sfondo • "+currentBike.name).setSingleChoiceItems(new String[]{"Africa Twin originale","Africa Twin blu","Adventure blu","Sportiva","Foto personale","Nessuno sfondo","BMW R 1300 GS","Suzuki V-Strom","Ducati Multistrada"},selected,(dialog,which)->{if(which==4){dialog.dismiss();openBackground.launch(new String[]{"image/*"});return;}getPreferences(MODE_PRIVATE).edit().putInt(key,which).apply();applyBikeBackground();dialog.dismiss();}).setNegativeButton("ANNULLA",null));}
    void applyBikeBackground(){if(currentBike==null||bikeBackgroundImage==null)return;int choice=getPreferences(MODE_PRIVATE).getInt("bike_background_"+currentBike.id,0);if(choice==0)bikeBackgroundImage.setImageResource(R.drawable.moto_africa_twin);else if(choice==1)bikeBackgroundImage.setImageResource(R.drawable.moto_africa_twin_blu);else if(choice==2)bikeBackgroundImage.setImageResource(R.drawable.moto_background);else if(choice==3)bikeBackgroundImage.setImageResource(R.drawable.moto_sportiva);else if(choice==4){String u=getPreferences(MODE_PRIVATE).getString("custom_background_"+currentBike.id,"");if(!u.isEmpty())bikeBackgroundImage.setImageURI(Uri.parse(u));}else if(choice==6)bikeBackgroundImage.setImageResource(R.drawable.moto_bmw_r1300gs);else if(choice==7)bikeBackgroundImage.setImageResource(R.drawable.moto_suzuki_vstrom);else if(choice==8)bikeBackgroundImage.setImageResource(R.drawable.moto_ducati_multistrada);else bikeBackgroundImage.setImageDrawable(null);}
    void changeBike(){String[] items=new String[bikes.size()+1];for(int i=0;i<bikes.size();i++)items[i]=(bikes.get(i).id==currentBike.id?"✓  ":"")+bikes.get(i).name;items[bikes.size()]="＋  Gestisci moto";showStyled(new AlertDialog.Builder(this).setTitle("Cambio moto").setItems(items,(d,which)->{if(which==bikes.size())manageBikes();else loadBikes(bikes.get(which).id);}).setNegativeButton("ANNULLA",null));}
    void backupMenu(){showStyled(new AlertDialog.Builder(this).setTitle("Backup").setItems(new String[]{"Salva backup","Ripristina backup"},(d,which)->{if(which==0)startBackupExport();else startBackupImport();}).setNegativeButton("ANNULLA",null));}
    void showAppInfo(){String v="?";try{v=getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception ignored){}showStyled(new AlertDialog.Builder(this).setTitle("Manutenzione Moto").setMessage("Versione "+v+"\n\nPaolo Free 1.0").setPositiveButton("OK",null));}
    void applyKeepScreenSetting(){boolean on=getPreferences(MODE_PRIVATE).getBoolean("keep_screen",false);if(on)getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);}
    void toggleKeepScreen(){boolean on=!getPreferences(MODE_PRIVATE).getBoolean("keep_screen",false);getPreferences(MODE_PRIVATE).edit().putBoolean("keep_screen",on).apply();applyKeepScreenSetting();Toast.makeText(this,on?"Schermo sempre acceso attivato":"Risparmio batteria attivato",Toast.LENGTH_LONG).show();}
    void showStats(){int y=Calendar.getInstance().get(Calendar.YEAR);StringBuilder s=new StringBuilder();for(int n=0;n<5;n++){int yy=y-n;s.append(yy).append("   ").append(euro.format(db.total(currentBike.id,yy))).append('\n');}startActivity(new Intent(this,StatsActivity.class).putExtra("bike_id",currentBike.id).putExtra("bike_name",currentBike.name));}
    void exportMenu(){showStyled(new AlertDialog.Builder(this).setTitle("Esporta storico").setItems(new String[]{"Documento PDF","Foglio CSV"},(d,w)->{String base="Storico_"+currentBike.name.replace(' ','_');if(w==0)createPdf.launch(base+".pdf");else createCsv.launch(base+".csv");}).setNegativeButton("ANNULLA",null));}
    void registerLaunchers(){
        createJson=registerForActivityResult(new ActivityResultContracts.CreateDocument("application/json"),u->{if(u!=null)writeJson(u);});
        openJson=registerForActivityResult(new ActivityResultContracts.GetContent(),u->{if(u!=null)readJson(u);});
        createCsv=registerForActivityResult(new ActivityResultContracts.CreateDocument("text/csv"),u->{if(u!=null)writeCsv(u);});
        createPdf=registerForActivityResult(new ActivityResultContracts.CreateDocument("application/pdf"),u->{if(u!=null)writePdf(u);});
        openPhoto=registerForActivityResult(new ActivityResultContracts.OpenDocument(),u->{if(u!=null){persist(u);pendingPhoto=u;Toast.makeText(this,"Scontrino allegato",Toast.LENGTH_SHORT).show();}});
        openBackground=registerForActivityResult(new ActivityResultContracts.OpenDocument(),u->{if(u!=null){persist(u);getPreferences(MODE_PRIVATE).edit().putString("custom_background_"+currentBike.id,u.toString()).putInt("bike_background_"+currentBike.id,4).apply();applyBikeBackground();}});
    }
    void persist(Uri u){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}
    void writeJson(Uri u){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(db.exportJson().toString(2).getBytes(StandardCharsets.UTF_8));Toast.makeText(this,"Backup salvato",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Errore backup",Toast.LENGTH_LONG).show();}}
    void readJson(Uri u){try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))>0)out.write(b,0,n);JSONObject j=new JSONObject(out.toString("UTF-8"));showStyled(new AlertDialog.Builder(this).setTitle("Ripristinare il backup?").setMessage("I dati presenti verranno sostituiti.").setNegativeButton("ANNULLA",null).setPositiveButton("RIPRISTINA",(d,w)->{try{db.importJson(j);loadBikes(0);}catch(Exception e){Toast.makeText(this,"Backup non valido",Toast.LENGTH_LONG).show();}}));}catch(Exception e){Toast.makeText(this,"Impossibile leggere il backup",Toast.LENGTH_LONG).show();}}
    void writeCsv(Uri u){try(OutputStream o=getContentResolver().openOutputStream(u)){StringBuilder s=new StringBuilder("Data;Intervento;Km;Costo;Eseguito da\n");for(MaintenanceDb.Entry e:db.all(currentBike.id,null))s.append(MaintenanceDb.formatDate(e.dateTs)).append(';').append(e.part.replace(';',',')).append(';').append(e.km).append(';').append(String.format(Locale.ITALY,"%.2f",e.cost)).append(';').append(e.who).append('\n');o.write(s.toString().getBytes(StandardCharsets.UTF_8));Toast.makeText(this,"CSV salvato",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Errore esportazione",Toast.LENGTH_LONG).show();}}
    void writePdf(Uri u){try{PdfDocument p=new PdfDocument();Paint x=new Paint(1);int page=1,row=0;PdfDocument.Page pg=null;android.graphics.Canvas c=null;for(MaintenanceDb.Entry e:db.all(currentBike.id,null)){if(row%25==0){if(pg!=null)p.finishPage(pg);pg=p.startPage(new PdfDocument.PageInfo.Builder(595,842,page++).create());c=pg.getCanvas();x.setColor(Color.rgb(5,8,15));c.drawColor(Color.rgb(5,8,15));x.setColor(Color.rgb(75,196,255));x.setTextSize(20);c.drawText("MANUTENZIONE • "+currentBike.name,35,45,x);x.setTextSize(11);}int y=80+(row%25)*29;x.setColor(Color.WHITE);c.drawText(MaintenanceDb.formatDate(e.dateTs)+"  "+e.part,35,y,x);x.setColor(Color.rgb(75,196,255));c.drawText(e.km+" km  "+euro.format(e.cost),390,y,x);row++;}if(pg!=null)p.finishPage(pg);if(row==0){pg=p.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());pg.getCanvas().drawText("Nessun intervento",35,60,x);p.finishPage(pg);}try(OutputStream o=getContentResolver().openOutputStream(u)){p.writeTo(o);}p.close();Toast.makeText(this,"PDF salvato",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Errore PDF",Toast.LENGTH_LONG).show();}}
    int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    void showOpeningAnimation(){
        View main=findViewById(R.id.mainRoot);main.setAlpha(0f);
        FrameLayout splash=new FrameLayout(this);splash.setBackgroundColor(Color.rgb(7,24,39));
        LinearLayout center=new LinearLayout(this);center.setOrientation(LinearLayout.VERTICAL);center.setGravity(Gravity.CENTER);center.setAlpha(0f);center.setScaleX(0.72f);center.setScaleY(0.72f);
        NeonMotoView logo=new NeonMotoView(this);center.addView(logo,new LinearLayout.LayoutParams(dp(220),dp(150)));
        TextView title=new TextView(this);title.setText("MANUTENZIONE MOTO");title.setTextColor(Color.WHITE);title.setTextSize(24);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER);LinearLayout.LayoutParams titleParams=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT);titleParams.topMargin=dp(18);center.addView(title,titleParams);
        TextView sub=new TextView(this);sub.setText("Il diario della tua moto");sub.setTextColor(Color.rgb(75,196,255));sub.setTextSize(15);sub.setGravity(Gravity.CENTER);center.addView(sub,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT));
        splash.addView(center,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
        addContentView(splash,new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
        center.animate().alpha(1f).scaleX(1f).scaleY(1f).setDuration(650).setInterpolator(new android.view.animation.OvershootInterpolator(0.8f)).start();
        splash.postDelayed(()->{main.animate().alpha(1f).setDuration(500).start();findViewById(R.id.heroPanel).startAnimation(AnimationUtils.loadAnimation(this,R.anim.intro_hero));splash.animate().alpha(0f).setDuration(500).withEndAction(()->{ViewGroup parent=(ViewGroup)splash.getParent();if(parent!=null)parent.removeView(splash);}).start();},1250);
    }
    void manageBikes(){showStyled(new AlertDialog.Builder(this).setTitle("Gestione moto").setItems(new String[]{"Aggiungi una moto","Rinomina "+currentBike.name,"Elimina "+currentBike.name},(d,which)->{if(which==0)bikeNameDialog(false);else if(which==1)bikeNameDialog(true);else deleteCurrentBike();}).setNegativeButton("CHIUDI",null));}
    void bikeNameDialog(boolean rename){EditText name=input("Nome moto",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);if(rename)name.setText(currentBike.name);FrameLayout w=new FrameLayout(this);w.setPadding(45,5,45,0);w.addView(name);AlertDialog d=new AlertDialog.Builder(this).setTitle(rename?"Rinomina moto":"Nuova moto").setView(w).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty()){name.setError("Inserisci un nome");return;}long id;if(rename){id=currentBike.id;db.renameBike(id,n);}else id=db.addBike(n);d.dismiss();loadBikes(id);}));d.show();styleDialogButtons(d);}
    void deleteCurrentBike(){if(bikes.size()<=1){Toast.makeText(this,"Deve rimanere almeno una moto",Toast.LENGTH_LONG).show();return;}showStyled(new AlertDialog.Builder(this).setTitle("Eliminare "+currentBike.name+"?").setMessage("Verranno eliminate anche tutte le sue manutenzioni e scadenze. Questa operazione non può essere annullata.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA TUTTO",(d,w)->{db.deleteBike(currentBike.id);loadBikes(0);}));}
    void startBackupExport(){createJson.launch("ManutenzioneMoto_backup_"+new SimpleDateFormat("yyyyMMdd",Locale.ITALY).format(new Date())+".json");}void startBackupImport(){openJson.launch("application/json");}
    class EntryAdapter extends BaseAdapter{
        public int getCount(){return entries.size();}public Object getItem(int p){return entries.get(p);}public long getItemId(int p){return entries.get(p).id;}
        public View getView(int p,View v,android.view.ViewGroup parent){if(v==null)v=getLayoutInflater().inflate(R.layout.item_maintenance,parent,false);MaintenanceDb.Entry e=entries.get(p);((TextView)v.findViewById(R.id.itemPart)).setText(e.part);((TextView)v.findViewById(R.id.itemCost)).setText(euro.format(e.cost));((TextView)v.findViewById(R.id.itemInfo)).setText(String.format(Locale.ITALY,"%,d km  •  %s  •  %s%s",e.km,e.who,MaintenanceDb.formatDate(e.dateTs),e.photoUri.isEmpty()?"":"  •  📎"));v.findViewById(R.id.itemMenu).setOnClickListener(q->entryMenu(q,e));return v;}
    }
    class DeadlineAdapter extends BaseAdapter{
        public int getCount(){return deadlines.size();}public Object getItem(int p){return deadlines.get(p);}public long getItemId(int p){return deadlines.get(p).id;}
        public View getView(int p,View v,android.view.ViewGroup parent){if(v==null)v=getLayoutInflater().inflate(R.layout.item_maintenance,parent,false);MaintenanceDb.Deadline e=deadlines.get(p);int rem=e.targetKm>0?e.targetKm-currentKm:Integer.MAX_VALUE;long days=e.dueTs>0?(e.dueTs-System.currentTimeMillis())/86400000:Long.MAX_VALUE;boolean due=rem<=0||days<0;boolean soon=rem<=e.prewarnKm||days<=30;int tone=due?Color.rgb(255,70,90):soon?Color.rgb(255,174,60):Color.rgb(64,235,255);((TextView)v.findViewById(R.id.itemPart)).setText(e.title);TextView right=v.findViewById(R.id.itemCost);right.setText(due?"SCADUTA":e.targetKm>0?String.format(Locale.ITALY,"%,d km",rem):days+" gg");right.setTextColor(tone);String info=(e.targetKm>0?"A "+String.format(Locale.ITALY,"%,d km",e.targetKm):"")+(e.dueTs>0?"  •  "+MaintenanceDb.formatDate(e.dueTs):"");((TextView)v.findViewById(R.id.itemInfo)).setText(info);ProgressBar bar=v.findViewById(R.id.itemProgress);bar.setVisibility(View.VISIBLE);bar.setProgressTintList(ColorStateList.valueOf(tone));bar.setProgress(e.targetKm>0?Math.max(0,Math.min(100,100-Math.max(0,rem)*100/Math.max(1,e.intervalKm>0?e.intervalKm:10000))):Math.max(0,Math.min(100,(int)(100-Math.max(0,days)*100/Math.max(1,e.intervalMonths*30)))));v.findViewById(R.id.itemMenu).setOnClickListener(q->deadlineMenu(q,e));return v;}
    }
    void entryMenu(View anchor,MaintenanceDb.Entry e){PopupMenu m=new PopupMenu(this,anchor);m.getMenu().add("Modifica");if(!e.photoUri.isEmpty())m.getMenu().add("Apri scontrino");m.getMenu().add("Elimina");m.setOnMenuItemClickListener(x->{if(x.getTitle().toString().startsWith("Modifica"))edit(e);else if(x.getTitle().toString().startsWith("Apri")){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(e.photoUri)).setDataAndType(Uri.parse(e.photoUri),"image/*").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(Exception z){Toast.makeText(this,"Foto non disponibile",Toast.LENGTH_LONG).show();}}else confirmDelete(e);return true;});m.show();}
    void deadlineMenu(View anchor,MaintenanceDb.Deadline e){PopupMenu m=new PopupMenu(this,anchor);m.getMenu().add("Registra intervento eseguito");m.getMenu().add("Modifica");m.getMenu().add("Elimina");m.setOnMenuItemClickListener(x->{String s=x.getTitle().toString();if(s.startsWith("Registra"))edit(null,e);else if(s.startsWith("Modifica"))editDeadline(e);else confirmDeleteDeadline(e);return true;});m.show();}
}
