package it.paolofree.manutenzionemoto;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.view.animation.AnimationUtils;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;
import androidx.core.content.ContextCompat;
import java.text.*;
import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.json.JSONObject;

public class MainActivity extends AppCompatActivity {
    MaintenanceDb db; List<MaintenanceDb.Entry> entries=new ArrayList<>(); List<MaintenanceDb.Deadline> deadlines=new ArrayList<>(); List<MaintenanceDb.Bike> bikes=new ArrayList<>(); MaintenanceDb.Bike currentBike; ImageView bikeBackgroundImage; ListView list; TextView empty,currentKmText,activeBikeText; String filter=null; boolean showDeadlines=false; int currentKm; static final int EXPORT_BACKUP=201,IMPORT_BACKUP=202;
    final NumberFormat euro=NumberFormat.getCurrencyInstance(Locale.ITALY);

    @Override public void onCreate(Bundle b){ super.onCreate(b); setContentView(R.layout.activity_main); getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        db=new MaintenanceDb(this); list=findViewById(R.id.list);empty=findViewById(R.id.emptyText);currentKmText=findViewById(R.id.currentKmText);activeBikeText=findViewById(R.id.activeBikeText);bikeBackgroundImage=findViewById(R.id.bikeBackgroundImage);
        loadBikes(0); createNotificationChannel(); requestNotificationPermission();
        findViewById(R.id.settingsButton).setOnClickListener(v->showSettings());
        findViewById(R.id.updateKmButton).setOnClickListener(v->updateCurrentKm());
        findViewById(R.id.addButton).setOnClickListener(v->{if(showDeadlines)editDeadline(null);else edit(null);});
        ((RadioGroup)findViewById(R.id.sectionGroup)).setOnCheckedChangeListener((g,id)->{showDeadlines=id==R.id.sectionDeadlines;findViewById(R.id.filterGroup).setVisibility(showDeadlines?View.GONE:View.VISIBLE);((Button)findViewById(R.id.addButton)).setText(showDeadlines?"＋  NUOVA SCADENZA":"＋  NUOVO INTERVENTO");refresh();});
        ((RadioGroup)findViewById(R.id.filterGroup)).setOnCheckedChangeListener((g,id)->{filter=id==R.id.filterShop?"Officina":id==R.id.filterMe?"Io":null; refresh();});
        list.setOnItemClickListener((p,v,pos,id)->{if(showDeadlines)editDeadline(deadlines.get(pos));else edit(entries.get(pos));});
        list.setOnItemLongClickListener((p,v,pos,id)->{ if(showDeadlines)confirmDeleteDeadline(deadlines.get(pos));else confirmDelete(entries.get(pos)); return true; }); refresh();
        showOpeningAnimation();
    }
    void refresh(){ if(currentBike==null)return;entries=db.all(currentBike.id,filter); deadlines=db.deadlines(currentBike.id);
        boolean none=showDeadlines?deadlines.isEmpty():entries.isEmpty(); empty.setText(showDeadlines?"Nessuna scadenza impostata\nPremi + per aggiungerne una":"Nessun intervento registrato\nPremi + per iniziare");empty.setVisibility(none?View.VISIBLE:View.GONE);list.setVisibility(none?View.GONE:View.VISIBLE);list.setAdapter(showDeadlines?new DeadlineAdapter():new EntryAdapter()); }
    TextView label(String s){ TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.rgb(156,179,195));t.setPadding(0,12,0,3);return t; }
    EditText input(String hint,int type){ EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(120,145,160));e.setInputType(type);e.setBackgroundResource(R.drawable.bg_input);return e; }
    void edit(MaintenanceDb.Entry old){
        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(45,5,45,0);
        EditText part=input("es. Olio e filtro",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);
        EditText km=input("es. 25000",InputType.TYPE_CLASS_NUMBER); EditText cost=input("es. 89,50",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);
        RadioGroup who=new RadioGroup(this);who.setOrientation(RadioGroup.HORIZONTAL); RadioButton shop=new RadioButton(this);shop.setText("Officina");shop.setTextColor(Color.WHITE); RadioButton me=new RadioButton(this);me.setText("Io");me.setTextColor(Color.WHITE);who.addView(shop);who.addView(me);shop.setChecked(true);
        box.addView(label("PEZZO / INTERVENTO"));box.addView(part);box.addView(label("CHILOMETRI"));box.addView(km);box.addView(label("COSTO (€)"));box.addView(cost);box.addView(label("ESEGUITO DA"));box.addView(who);
        if(old!=null){part.setText(old.part);km.setText(String.valueOf(old.km));cost.setText(String.format(Locale.ITALY,"%.2f",old.cost));(old.who.equals("Io")?me:shop).setChecked(true);}
        AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Nuovo intervento":"Modifica intervento").setView(box).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();
        d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
            String p=part.getText().toString().trim(),ks=km.getText().toString().trim(),cs=cost.getText().toString().trim().replace(',','.');
            if(p.isEmpty()){part.setError("Inserisci il pezzo o intervento");return;} if(ks.isEmpty()){km.setError("Inserisci i km");return;} if(cs.isEmpty()){cost.setError("Inserisci il costo");return;}
            try{int kval=Integer.parseInt(ks);double cval=Double.parseDouble(cs);String w=me.isChecked()?"Io":"Officina";String date=old==null?new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date()):old.date;db.save(old==null?null:old.id,currentBike.id,p,kval,cval,w,date);d.dismiss();refresh();}catch(Exception ex){cost.setError("Valore non valido");}
        }));d.show();
    }
    void confirmDelete(MaintenanceDb.Entry e){new AlertDialog.Builder(this).setTitle("Eliminare?").setMessage(e.part+" verrà cancellato.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA",(d,w)->{db.delete(e.id);refresh();}).show();}
    void updateCurrentKm(){final EditText km=input("Chilometri attuali",InputType.TYPE_CLASS_NUMBER);km.setText(String.valueOf(currentKm));FrameLayout wrap=new FrameLayout(this);wrap.setPadding(45,5,45,0);wrap.addView(km);AlertDialog d=new AlertDialog.Builder(this).setTitle("Km • "+currentBike.name).setView(wrap).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{int value=Integer.parseInt(km.getText().toString());if(value<0)throw new Exception();currentKm=value;currentBike.km=value;db.updateBikeKm(currentBike.id,value);currentKmText.setText(String.format(Locale.ITALY,"%,d km",value));d.dismiss();checkDeadlines();refresh();}catch(Exception ex){km.setError("Inserisci chilometri validi");}}));d.show();}
    void editDeadline(MaintenanceDb.Deadline old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(45,5,45,0);EditText title=input("es. Cambio olio",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);EditText target=input("es. 30000",InputType.TYPE_CLASS_NUMBER);box.addView(label("INTERVENTO / PEZZO"));box.addView(title);box.addView(label("SCADENZA A KM"));box.addView(target);if(old!=null){title.setText(old.title);target.setText(String.valueOf(old.targetKm));}AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"Nuova scadenza":"Modifica scadenza").setView(box).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String t=title.getText().toString().trim();if(t.isEmpty()){title.setError("Inserisci l'intervento");return;}try{int k=Integer.parseInt(target.getText().toString());db.saveDeadline(old==null?null:old.id,currentBike.id,t,k);d.dismiss();checkDeadlines();refresh();}catch(Exception ex){target.setError("Inserisci i km della scadenza");}}));d.show();}
    void confirmDeleteDeadline(MaintenanceDb.Deadline e){new AlertDialog.Builder(this).setTitle("Eliminare scadenza?").setMessage(e.title+" verrà cancellata.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA",(d,w)->{db.deleteDeadline(e.id);refresh();}).show();}
    void createNotificationChannel(){if(android.os.Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("maintenance_due","Scadenze manutenzione",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Avvisi al raggiungimento dei chilometri");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    void requestNotificationPermission(){if(android.os.Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},100);}
    void checkDeadlines(){for(MaintenanceDb.Deadline e:db.deadlines(currentBike.id))if(!e.notified&&currentKm>=e.targetKm){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,(int)e.id,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);NotificationCompat.Builder n=new NotificationCompat.Builder(this,"maintenance_due").setSmallIcon(R.drawable.ic_launcher).setContentTitle(currentBike.name+": manutenzione in scadenza").setContentText(e.title+" • prevista a "+String.format(Locale.ITALY,"%,d km",e.targetKm)).setPriority(NotificationCompat.PRIORITY_HIGH).setAutoCancel(true).setContentIntent(pi);if(ContextCompat.checkSelfPermission(this,android.Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED){NotificationManagerCompat.from(this).notify((int)e.id,n.build());db.markNotified(e.id);}}}
    void loadBikes(long selectId){bikes=db.bikes();if(bikes.isEmpty()){db.addBike("La mia moto");bikes=db.bikes();}if(selectId==0)selectId=getPreferences(MODE_PRIVATE).getLong("active_bike",bikes.get(0).id);int pos=0;for(int i=0;i<bikes.size();i++)if(bikes.get(i).id==selectId)pos=i;currentBike=bikes.get(pos);getPreferences(MODE_PRIVATE).edit().putLong("active_bike",currentBike.id).apply();int old=getPreferences(MODE_PRIVATE).getInt("current_km",0);if(currentBike.id==1&&currentBike.km==0&&old>0){db.updateBikeKm(1,old);currentBike.km=old;getPreferences(MODE_PRIVATE).edit().remove("current_km").apply();}currentKm=currentBike.km;activeBikeText.setText(currentBike.name);currentKmText.setText(String.format(Locale.ITALY,"%,d km",currentKm));applyBikeBackground();refresh();}
    void showSettings(){new AlertDialog.Builder(this).setTitle("Impostazioni").setItems(new String[]{"Cambio moto","Sfondo moto","Backup e ripristino","Versione 1.7","Firma • Paolo Free 1.0"},(d,which)->{if(which==0)changeBike();else if(which==1)chooseBikeBackground();else if(which==2)backupMenu();else if(which==3||which==4)showAppInfo();}).setNegativeButton("CHIUDI",null).show();}
    void chooseBikeBackground(){String key="bike_background_"+currentBike.id;int selected=getPreferences(MODE_PRIVATE).getInt(key,0);new AlertDialog.Builder(this).setTitle("Sfondo • "+currentBike.name).setSingleChoiceItems(new String[]{"Africa Twin originale","Africa Twin blu","Adventure blu","Sportiva","Nessuno sfondo"},selected,(dialog,which)->{getPreferences(MODE_PRIVATE).edit().putInt(key,which).apply();applyBikeBackground();dialog.dismiss();}).setNegativeButton("ANNULLA",null).show();}
    void applyBikeBackground(){if(currentBike==null||bikeBackgroundImage==null)return;int choice=getPreferences(MODE_PRIVATE).getInt("bike_background_"+currentBike.id,0);if(choice==0)bikeBackgroundImage.setImageResource(R.drawable.moto_africa_twin);else if(choice==1)bikeBackgroundImage.setImageResource(R.drawable.moto_africa_twin_blu);else if(choice==2)bikeBackgroundImage.setImageResource(R.drawable.moto_background);else if(choice==3)bikeBackgroundImage.setImageResource(R.drawable.moto_sportiva);else bikeBackgroundImage.setImageDrawable(null);}
    void changeBike(){String[] items=new String[bikes.size()+1];for(int i=0;i<bikes.size();i++)items[i]=(bikes.get(i).id==currentBike.id?"✓  ":"")+bikes.get(i).name;items[bikes.size()]="＋  Gestisci moto";new AlertDialog.Builder(this).setTitle("Cambio moto").setItems(items,(d,which)->{if(which==bikes.size())manageBikes();else loadBikes(bikes.get(which).id);}).setNegativeButton("ANNULLA",null).show();}
    void backupMenu(){new AlertDialog.Builder(this).setTitle("Backup").setItems(new String[]{"Salva backup","Ripristina backup"},(d,which)->{if(which==0)startBackupExport();else startBackupImport();}).setNegativeButton("ANNULLA",null).show();}
    void showAppInfo(){new AlertDialog.Builder(this).setTitle("Manutenzione Moto").setMessage("Versione 1.7\n\nPaolo Free 1.0").setPositiveButton("OK",null).show();}
    int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    void showOpeningAnimation(){
        View main=findViewById(R.id.mainRoot);main.setAlpha(0f);
        FrameLayout splash=new FrameLayout(this);splash.setBackgroundColor(Color.rgb(7,24,39));
        LinearLayout center=new LinearLayout(this);center.setOrientation(LinearLayout.VERTICAL);center.setGravity(Gravity.CENTER);center.setAlpha(0f);center.setScaleX(0.72f);center.setScaleY(0.72f);
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ic_launcher);center.addView(logo,new LinearLayout.LayoutParams(dp(132),dp(132)));
        TextView title=new TextView(this);title.setText("MANUTENZIONE MOTO");title.setTextColor(Color.WHITE);title.setTextSize(24);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER);LinearLayout.LayoutParams titleParams=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT);titleParams.topMargin=dp(18);center.addView(title,titleParams);
        TextView sub=new TextView(this);sub.setText("Il diario della tua moto");sub.setTextColor(Color.rgb(75,196,255));sub.setTextSize(15);sub.setGravity(Gravity.CENTER);center.addView(sub,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT));
        splash.addView(center,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
        addContentView(splash,new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
        center.animate().alpha(1f).scaleX(1f).scaleY(1f).setDuration(650).setInterpolator(new android.view.animation.OvershootInterpolator(0.8f)).start();
        splash.postDelayed(()->{main.animate().alpha(1f).setDuration(500).start();findViewById(R.id.heroPanel).startAnimation(AnimationUtils.loadAnimation(this,R.anim.intro_hero));splash.animate().alpha(0f).setDuration(500).withEndAction(()->{ViewGroup parent=(ViewGroup)splash.getParent();if(parent!=null)parent.removeView(splash);}).start();},1250);
    }
    void manageBikes(){new AlertDialog.Builder(this).setTitle("Gestione moto").setItems(new String[]{"Aggiungi una moto","Rinomina "+currentBike.name,"Elimina "+currentBike.name},(d,which)->{if(which==0)bikeNameDialog(false);else if(which==1)bikeNameDialog(true);else deleteCurrentBike();}).setNegativeButton("CHIUDI",null).show();}
    void bikeNameDialog(boolean rename){EditText name=input("Nome moto",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);if(rename)name.setText(currentBike.name);FrameLayout w=new FrameLayout(this);w.setPadding(45,5,45,0);w.addView(name);AlertDialog d=new AlertDialog.Builder(this).setTitle(rename?"Rinomina moto":"Nuova moto").setView(w).setNegativeButton("ANNULLA",null).setPositiveButton("SALVA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty()){name.setError("Inserisci un nome");return;}long id;if(rename){id=currentBike.id;db.renameBike(id,n);}else id=db.addBike(n);d.dismiss();loadBikes(id);}));d.show();}
    void deleteCurrentBike(){if(bikes.size()<=1){Toast.makeText(this,"Deve rimanere almeno una moto",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("Eliminare "+currentBike.name+"?").setMessage("Verranno eliminate anche tutte le sue manutenzioni e scadenze. Questa operazione non può essere annullata.").setNegativeButton("ANNULLA",null).setPositiveButton("ELIMINA TUTTO",(d,w)->{db.deleteBike(currentBike.id);loadBikes(0);}).show();}
    void startBackupExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"ManutenzioneMoto_backup_"+new SimpleDateFormat("yyyyMMdd",Locale.ITALY).format(new Date())+".json");startActivityForResult(i,EXPORT_BACKUP);}
    void startBackupImport(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_BACKUP);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(requestCode==EXPORT_BACKUP){try(OutputStream o=getContentResolver().openOutputStream(uri)){o.write(db.exportJson().toString(2).getBytes(StandardCharsets.UTF_8));Toast.makeText(this,"Backup salvato",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Errore durante il backup",Toast.LENGTH_LONG).show();}}else if(requestCode==IMPORT_BACKUP){try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[4096];int n;while((n=in.read(buf))>0)out.write(buf,0,n);JSONObject backup=new JSONObject(out.toString("UTF-8"));new AlertDialog.Builder(this).setTitle("Ripristinare il backup?").setMessage("I dati presenti nell'app verranno sostituiti con quelli del backup.").setNegativeButton("ANNULLA",null).setPositiveButton("RIPRISTINA",(d,w)->{try{db.importJson(backup);loadBikes(0);Toast.makeText(this,"Backup ripristinato",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Backup non valido",Toast.LENGTH_LONG).show();}}).show();}catch(Exception e){Toast.makeText(this,"Impossibile leggere il backup",Toast.LENGTH_LONG).show();}}}
    class EntryAdapter extends BaseAdapter{
        public int getCount(){return entries.size();}public Object getItem(int p){return entries.get(p);}public long getItemId(int p){return entries.get(p).id;}
        public View getView(int p,View v,android.view.ViewGroup parent){if(v==null)v=getLayoutInflater().inflate(R.layout.item_maintenance,parent,false);MaintenanceDb.Entry e=entries.get(p);((TextView)v.findViewById(R.id.itemPart)).setText(e.part);((TextView)v.findViewById(R.id.itemCost)).setText(euro.format(e.cost));((TextView)v.findViewById(R.id.itemInfo)).setText(String.format(Locale.ITALY,"%,d km  •  %s  •  %s",e.km,e.who,e.date));return v;}
    }
    class DeadlineAdapter extends BaseAdapter{
        public int getCount(){return deadlines.size();}public Object getItem(int p){return deadlines.get(p);}public long getItemId(int p){return deadlines.get(p).id;}
        public View getView(int p,View v,android.view.ViewGroup parent){if(v==null)v=getLayoutInflater().inflate(R.layout.item_maintenance,parent,false);MaintenanceDb.Deadline e=deadlines.get(p);int remaining=e.targetKm-currentKm;((TextView)v.findViewById(R.id.itemPart)).setText(e.title);TextView right=v.findViewById(R.id.itemCost);right.setText(remaining<=0?"SCADUTA":String.format(Locale.ITALY,"%,d km",remaining));right.setTextColor(remaining<=0?Color.rgb(255,107,107):Color.rgb(75,196,255));((TextView)v.findViewById(R.id.itemInfo)).setText("Scadenza a "+String.format(Locale.ITALY,"%,d km",e.targetKm)+(remaining<=0?"  •  raggiunta":"  •  mancanti"));return v;}
    }
}
