package it.paolofree.manutenzionemoto;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MaintenanceDb extends SQLiteOpenHelper {
 public static class Bike { public long id; public String name; public int km; Bike(long i,String n,int k){id=i;name=n;km=k;} public String toString(){return name;} }
 public static class Entry { public long id,bikeId,dateTs; public String part,who,photoUri; public int km; public double cost; Entry(long i,long b,String p,int k,double c,String w,long d,String u){id=i;bikeId=b;part=p;km=k;cost=c;who=w;dateTs=d;photoUri=u;} }
 public static class Deadline { public long id,bikeId,dueTs; public String title; public int targetKm,intervalKm,intervalMonths,prewarnKm,notifyState; Deadline(long i,long b,String t,int k,long due,int ik,int im,int pre,int ns){id=i;bikeId=b;title=t;targetKm=k;dueTs=due;intervalKm=ik;intervalMonths=im;prewarnKm=pre;notifyState=ns;} }
 MaintenanceDb(Context c){super(c,"maintenance.db",null,5);}
 public void onCreate(SQLiteDatabase d){
  d.execSQL("CREATE TABLE bikes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,current_km INTEGER NOT NULL DEFAULT 0)");d.execSQL("INSERT INTO bikes(name,current_km) VALUES('La mia moto',0)");
  d.execSQL("CREATE TABLE entries(id INTEGER PRIMARY KEY AUTOINCREMENT,part TEXT NOT NULL,km INTEGER NOT NULL,cost REAL NOT NULL,who TEXT NOT NULL,date TEXT NOT NULL DEFAULT '',bike_id INTEGER NOT NULL DEFAULT 1,date_ts INTEGER NOT NULL DEFAULT 0,photo_uri TEXT NOT NULL DEFAULT '')");
  d.execSQL("CREATE TABLE deadlines(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,target_km INTEGER NOT NULL DEFAULT 0,notified INTEGER NOT NULL DEFAULT 0,bike_id INTEGER NOT NULL DEFAULT 1,due_ts INTEGER NOT NULL DEFAULT 0,interval_km INTEGER NOT NULL DEFAULT 0,interval_months INTEGER NOT NULL DEFAULT 0,prewarn_km INTEGER NOT NULL DEFAULT 500,notify_state INTEGER NOT NULL DEFAULT 0)");
 }
 public void onUpgrade(SQLiteDatabase d,int o,int n){if(o<2)d.execSQL("CREATE TABLE deadlines(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,target_km INTEGER NOT NULL,notified INTEGER NOT NULL DEFAULT 0)");if(o<3){d.execSQL("CREATE TABLE bikes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,current_km INTEGER NOT NULL DEFAULT 0)");d.execSQL("INSERT INTO bikes(name,current_km) VALUES('La mia moto',0)");d.execSQL("ALTER TABLE entries ADD COLUMN bike_id INTEGER NOT NULL DEFAULT 1");d.execSQL("ALTER TABLE deadlines ADD COLUMN bike_id INTEGER NOT NULL DEFAULT 1");}if(o<4){d.execSQL("ALTER TABLE entries ADD COLUMN date_ts INTEGER NOT NULL DEFAULT 0");d.execSQL("ALTER TABLE entries ADD COLUMN photo_uri TEXT NOT NULL DEFAULT ''");migrateDates(d);}if(o<5){d.execSQL("ALTER TABLE deadlines ADD COLUMN due_ts INTEGER NOT NULL DEFAULT 0");d.execSQL("ALTER TABLE deadlines ADD COLUMN interval_km INTEGER NOT NULL DEFAULT 0");d.execSQL("ALTER TABLE deadlines ADD COLUMN interval_months INTEGER NOT NULL DEFAULT 0");d.execSQL("ALTER TABLE deadlines ADD COLUMN prewarn_km INTEGER NOT NULL DEFAULT 500");d.execSQL("ALTER TABLE deadlines ADD COLUMN notify_state INTEGER NOT NULL DEFAULT 0");d.execSQL("UPDATE deadlines SET notify_state=CASE WHEN notified=1 THEN 2 ELSE 0 END");}}
 private void migrateDates(SQLiteDatabase d){try(Cursor c=d.rawQuery("SELECT id,date FROM entries",null)){SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY);while(c.moveToNext()){long ts;try{Date x=f.parse(c.getString(1));ts=x==null?System.currentTimeMillis():x.getTime();}catch(Exception e){ts=System.currentTimeMillis();}ContentValues v=new ContentValues();v.put("date_ts",ts);d.update("entries",v,"id=?",a(c.getLong(0)));}}}
 List<Bike> bikes(){List<Bike> z=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,current_km FROM bikes ORDER BY id",null)){while(c.moveToNext())z.add(new Bike(c.getLong(0),c.getString(1),c.getInt(2)));}return z;}
 long addBike(String n){ContentValues v=new ContentValues();v.put("name",n);return getWritableDatabase().insert("bikes",null,v);} void renameBike(long id,String n){ContentValues v=new ContentValues();v.put("name",n);getWritableDatabase().update("bikes",v,"id=?",a(id));} void updateBikeKm(long id,int k){ContentValues v=new ContentValues();v.put("current_km",k);getWritableDatabase().update("bikes",v,"id=?",a(id));}
 void deleteBike(long id){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.delete("entries","bike_id=?",a(id));d.delete("deadlines","bike_id=?",a(id));d.delete("bikes","id=?",a(id));d.setTransactionSuccessful();}finally{d.endTransaction();}}
 long save(Long id,long bike,String p,int km,double cost,String who,long ts,String photo){ContentValues v=new ContentValues();v.put("bike_id",bike);v.put("part",p);v.put("km",km);v.put("cost",cost);v.put("who",who);v.put("date_ts",ts);v.put("date",formatDate(ts));v.put("photo_uri",photo==null?"":photo);if(id==null)return getWritableDatabase().insert("entries",null,v);getWritableDatabase().update("entries",v,"id=?",a(id));return id;}
 void delete(long id){getWritableDatabase().delete("entries","id=?",a(id));}
 List<Entry> all(long bike,String who){List<Entry> z=new ArrayList<>();String s="bike_id=?"+(who==null?"":" AND who=?");String[] aa=who==null?a(bike):new String[]{""+bike,who};try(Cursor c=getReadableDatabase().query("entries",null,s,aa,null,null,"date_ts DESC,km DESC,id DESC")){while(c.moveToNext())z.add(new Entry(g(c,"id"),g(c,"bike_id"),str(c,"part"),i(c,"km"),dbl(c,"cost"),str(c,"who"),g(c,"date_ts"),str(c,"photo_uri")));}return z;}
 long saveDeadline(Long id,long bike,String t,int target,long due,int ik,int im,int pre){ContentValues v=new ContentValues();v.put("bike_id",bike);v.put("title",t);v.put("target_km",target);v.put("due_ts",due);v.put("interval_km",ik);v.put("interval_months",im);v.put("prewarn_km",pre);v.put("notify_state",0);v.put("notified",0);if(id==null)return getWritableDatabase().insert("deadlines",null,v);getWritableDatabase().update("deadlines",v,"id=?",a(id));return id;}
 List<Deadline> deadlines(long bike){List<Deadline> z=new ArrayList<>();try(Cursor c=getReadableDatabase().query("deadlines",null,"bike_id=?",a(bike),null,null,"CASE WHEN target_km=0 THEN 1 ELSE 0 END,target_km,due_ts")){while(c.moveToNext())z.add(readD(c));}return z;} Deadline deadline(long id){try(Cursor c=getReadableDatabase().query("deadlines",null,"id=?",a(id),null,null,null)){return c.moveToFirst()?readD(c):null;}}
 void completeDeadline(long id,int doneKm){Deadline e=deadline(id);if(e==null)return;if(e.intervalKm<=0&&e.intervalMonths<=0){deleteDeadline(id);return;}long due=e.dueTs;if(e.intervalMonths>0){Calendar c=Calendar.getInstance();c.setTimeInMillis(due>0?due:System.currentTimeMillis());c.add(Calendar.MONTH,e.intervalMonths);due=c.getTimeInMillis();}ContentValues v=new ContentValues();v.put("target_km",e.intervalKm>0?doneKm+e.intervalKm:e.targetKm);v.put("due_ts",due);v.put("notify_state",0);v.put("notified",0);getWritableDatabase().update("deadlines",v,"id=?",a(id));}
 void deleteDeadline(long id){getWritableDatabase().delete("deadlines","id=?",a(id));} void setNotifyState(long id,int s){ContentValues v=new ContentValues();v.put("notify_state",s);getWritableDatabase().update("deadlines",v,"id=?",a(id));}
 double total(long bike,int year){Calendar f=Calendar.getInstance();f.clear();f.set(year,0,1);Calendar t=Calendar.getInstance();t.clear();t.set(year+1,0,1);try(Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(cost),0) FROM entries WHERE bike_id=? AND date_ts>=? AND date_ts<?",new String[]{""+bike,""+f.getTimeInMillis(),""+t.getTimeInMillis()})){c.moveToFirst();return c.getDouble(0);}}
 static String formatDate(long ts){return new SimpleDateFormat("dd/MM/yyyy",Locale.ITALY).format(new Date(ts));}
 JSONObject exportJson()throws JSONException{JSONObject r=new JSONObject().put("format","manutenzione-moto").put("version",2);JSONArray b=new JSONArray(),e=new JSONArray(),d=new JSONArray();for(Bike x:bikes())b.put(new JSONObject().put("id",x.id).put("name",x.name).put("km",x.km));try(Cursor c=getReadableDatabase().query("entries",null,null,null,null,null,"id")){while(c.moveToNext())e.put(new JSONObject().put("id",g(c,"id")).put("bike",g(c,"bike_id")).put("part",str(c,"part")).put("km",i(c,"km")).put("cost",dbl(c,"cost")).put("who",str(c,"who")).put("dateTs",g(c,"date_ts")).put("photo",str(c,"photo_uri")));}try(Cursor c=getReadableDatabase().query("deadlines",null,null,null,null,null,"id")){while(c.moveToNext()){Deadline x=readD(c);d.put(new JSONObject().put("id",x.id).put("bike",x.bikeId).put("title",x.title).put("target",x.targetKm).put("due",x.dueTs).put("intervalKm",x.intervalKm).put("intervalMonths",x.intervalMonths).put("prewarn",x.prewarnKm).put("notify",x.notifyState));}}return r.put("bikes",b).put("entries",e).put("deadlines",d);}
 void importJson(JSONObject r)throws Exception{if(!"manutenzione-moto".equals(r.optString("format")))throw new Exception();JSONArray bs=r.getJSONArray("bikes"),es=r.getJSONArray("entries"),ds=r.getJSONArray("deadlines");SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.delete("entries",null,null);d.delete("deadlines",null,null);d.delete("bikes",null,null);for(int n=0;n<bs.length();n++){JSONObject o=bs.getJSONObject(n);d.execSQL("INSERT INTO bikes(id,name,current_km) VALUES(?,?,?)",new Object[]{o.getLong("id"),o.getString("name"),o.getInt("km")});}for(int n=0;n<es.length();n++){JSONObject o=es.getJSONObject(n);long ts=o.optLong("dateTs",System.currentTimeMillis());d.execSQL("INSERT INTO entries(id,part,km,cost,who,date,bike_id,date_ts,photo_uri) VALUES(?,?,?,?,?,?,?,?,?)",new Object[]{o.getLong("id"),o.getString("part"),o.getInt("km"),o.getDouble("cost"),o.getString("who"),formatDate(ts),o.getLong("bike"),ts,o.optString("photo")});}for(int n=0;n<ds.length();n++){JSONObject o=ds.getJSONObject(n);d.execSQL("INSERT INTO deadlines(id,title,target_km,notified,bike_id,due_ts,interval_km,interval_months,prewarn_km,notify_state) VALUES(?,?,?,?,?,?,?,?,?,?)",new Object[]{o.getLong("id"),o.getString("title"),o.optInt("target"),0,o.getLong("bike"),o.optLong("due"),o.optInt("intervalKm"),o.optInt("intervalMonths"),o.optInt("prewarn",500),o.optInt("notify")});}d.setTransactionSuccessful();}finally{d.endTransaction();}}
 private Deadline readD(Cursor c){return new Deadline(g(c,"id"),g(c,"bike_id"),str(c,"title"),i(c,"target_km"),g(c,"due_ts"),i(c,"interval_km"),i(c,"interval_months"),i(c,"prewarn_km"),i(c,"notify_state"));}private static String[] a(long x){return new String[]{""+x};}private static long g(Cursor c,String n){int x=c.getColumnIndex(n);return x<0?0:c.getLong(x);}private static int i(Cursor c,String n){return(int)g(c,n);}private static double dbl(Cursor c,String n){int x=c.getColumnIndex(n);return x<0?0:c.getDouble(x);}private static String str(Cursor c,String n){int x=c.getColumnIndex(n);return x<0||c.isNull(x)?"":c.getString(x);}
}
